### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [IBM/IPFSfB#1]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
Closing as the repo setting is `sudo: required`.
Feel free to reopen it.

**Comment by cclauss** [comment]
__sudo__ is completely deprecated in Travis CI as discuss in the URL above.  The ability to use the sudo command is _always_ on and there is no way to turn it off.
