### ISSUE TITLE
mdns error

### ISSUE THREAD

**Issue by iliasioannou** [IBM/IPFSfB#5]
- https://github.com/ipfs/go-ipfs/issues/1807
- https://github.com/ipfs/go-ipfs/issues/6359

The IPFS image needs to be pulled from master.

![image](https://user-images.githubusercontent.com/3886244/59668733-44289b80-91b9-11e9-9abf-703ec81d2836.png)

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
Closing as this repo always fetches with the latest go-ipfs release.
